const footerTranslations = {
    en: {
      tmdb: 'TMDB',
      description: 'It is a website to present some Movies.',
      navigation: 'Navigation',
      services: 'Services',
      myWork: 'My Work',
      aboutUs: 'About Us',
      blog: 'Blog',
      more: 'More',
      faqs: 'FAQs',
      privacyPolicy: 'Privacy & Policy',
      tasks: 'Tasks',
      contact: 'Contact',
      address: 'Tanta - Egypt',
      phone: '+201122348017',
      legal: 'Legal',
      termsOfUse: 'Terms of Use',
      cookiePolicy: 'Cookie Policy',
      rightsReserved: '© Agency2023. All rights reserved',
    },
    ar: {
      tmdb: 'TMDB',
      description: 'إنها موقع لتقديم بعض الأفلام.',
      navigation: 'التنقل',
      services: 'الخدمات',
      myWork: 'عملي',
      aboutUs: 'من نحن',
      blog: 'المدونة',
      more: 'المزيد',
      faqs: 'الأسئلة الشائعة',
      privacyPolicy: 'الخصوصية والسياسة',
      tasks: 'المهام',
      contact: 'اتصل بنا',
      address: 'طنطا - مصر',
      phone: '+201122348017',
      legal: 'قانوني',
      termsOfUse: 'شروط الاستخدام',
      cookiePolicy: 'سياسة ملفات الكوكيز',
      rightsReserved: '© Agency2023. جميع الحقوق محفوظة',
    },
    es: {
      tmdb: 'TMDB',
      description: 'Es un sitio web para presentar algunas películas.',
      navigation: 'Navegación',
      services: 'Servicios',
      myWork: 'Mi trabajo',
      aboutUs: 'Sobre nosotros',
      blog: 'Blog',
      more: 'Más',
      faqs: 'Preguntas frecuentes',
      privacyPolicy: 'Política de privacidad',
      tasks: 'Tareas',
      contact: 'Contacto',
      address: 'Tanta - Egipto',
      phone: '+201122348017',
      legal: 'Legal',
      termsOfUse: 'Términos de uso',
      cookiePolicy: 'Política de cookies',
      rightsReserved: '© Agency2023. Todos los derechos reservados',
    },
  };
  
  export { footerTranslations };